version: '3'


services:
  web:
    image: php7.4-apache:projet
    container_name: grp2-php-apache
    env_file: ./.env
    ports:
      # local:container
      - "1337:80"
    environment: 
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - COMPOSER_ALLOW_SUPERUSER=1
    volumes:
      # Volume stockant les fichiers web du projet
      - ./:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      # Lien vers le conteneur "db" (déclaré ci-après)
      - db:db

  pma:
    image: phpmyadmin
    container_name: grp2-phpmyadmin
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 1024M
    ports:
      - "8080:80"
    links:
      - db:db

  db:
    image: mysql:latest
    container_name: grp2-mysql
    ports:
      - "3306:3306"
    env_file: ./.env
    volumes:
      # Volume de la base de données
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: $USER_PASS
      # MYSQL_RANDOM_ROOT_PASSWORD: "yes"
   
volumes:
  mysql:
