name: GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.GITHUBTOSRVPRIVATEKEY }}" > ~/.ssh/id_rsa
      - name: Deploy
        run: |
          ssh -o StrictHostKeychecking=no grp2@groupe2.ais1-bordeaux.fr
          cd Docker/SimplonAisDocker
          git pull
